
pollutants:
    path: '/pollutants/'
    controller: AppBundle\Controller\PollutantController::getPollutants

pollutant_item:
    path: '/pollutants/{id}'
    controller: AppBundle\Controller\PollutantController::getPollutant

registers:
    path: '/annual_registers/'
    controller: AppBundle\Controller\AnnualRegisterController::getAnnualRegisters

register_item:
    path: '/annual_registers/{id}'
    controller: AppBundle\Controller\AnnualRegisterController::getAnnualRegister

