app:
    resource: '@AppBundle/Controller/'
    type: annotation

pollutants:
    path: '/pollutants/'
    controller: AppBundle\Controller\PollutantController::getPollutants
    methods: GET

pollutant_item:
    path: '/pollutant/{name}'
    controller: AppBundle\Controller\PollutantController::getPollutant
    methods: GET

registers:
    path: '/annual_registers/'
    controller: AppBundle\Controller\AnnualRegisterController::getAnnualRegisters
    methods: GET

register_item:
    path: '/annual_register/{idPollutant}-{idWeatherStation}'
    controller: AppBundle\Controller\AnnualRegisterController::getAnnualRegister
    methods: GET
